package com.myspace.risk;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidPeriod implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Start Date")
	private java.util.Date startDate;
	@org.kie.api.definition.type.Label(value = "End Date")
	private java.util.Date endDate;

	public ValidPeriod() {
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public ValidPeriod(java.util.Date startDate, java.util.Date endDate) {
		this.startDate = startDate;
		this.endDate = endDate;
	}

}